global_frame: map
robot_base_frame: base_footprint
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

obstacle_range: 3 #0.01
raytrace_range: 6 #0.2

footprint: [[0.15, 0.12], [0.15, -0.15], [-0.12, -0.15], [-0.12, 0.12]]
robot_radius: 0.30
inflation_radius: 0.1 #0.1 map shell
cost_scaling_factor: 3.0

map_type: costmap
transform_tolerance: 0.5
# observation_sources: scan

# scan: {  
#   sensor_frame: Lidar_1,
#   data_type: LaserScan,
#   topic: scan,
#   marking: true,
#   clearing: true,
#   }

inflater_layer:
  inflation_radius: 0.1
  cost_scaling_factor: 0.5

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {
    sensor_frame: Lidar_1, 
    data_type: LaserScan, 
    topic: scan, 
    marking: true, 
    clearing: true, 
    max_obstacle_height: 3, 
    min_obstacle_height: -3, 
    inf_is_valid: true, 
    obstacle_range: 2.5, 
    combination_method: 0,
    raytrace_range: 3}    

#layer definitions
static:
    enable: true
    map_topic: /map
    subscribe_to_updates: true

# footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
# footprint_padding: 0.01

# robot_base_frame: base_link
# update_frequency: 4.0
# publish_frequency: 3.0
# transform_tolerance: 0.5

# resolution: 0.05

# obstacle_range: 5.5
# raytrace_range: 6.0

# #layer definitions
# static:
#     enable: true
#     map_topic: /map
#     subscribe_to_updates: true

# obstacles_laser:
#     enabled: true
#     observation_sources: laser
#     laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

# inflation:
#     enabled: true
#     inflation_radius: 1.0
