obstacle_range: 0.01
raytrace_range: 0.2
footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
#robot_radius: ir_of_robot
inflation_radius: 0.1

transform_tolerance: 0.3
observation_sources: scan
scan: {  
  sensor_frame: Lidar_1,
  data_type: LaserScan,
  topic: scan,
  marking: true,
  clearing: true,
  }

# footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
# footprint_padding: 0.01

# robot_base_frame: base_link
# update_frequency: 4.0
# publish_frequency: 3.0
# transform_tolerance: 0.5

# resolution: 0.05

# obstacle_range: 5.5
# raytrace_range: 6.0

# #layer definitions
# static:
#     enable: true
#     map_topic: /map
#     subscribe_to_updates: true

# obstacles_laser:
#     enabled: true
#     observation_sources: laser
#     laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

# inflation:
#     enabled: true
#     inflation_radius: 1.0
