obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: scan
scan: 
  sensor_frame: Lidar_1,
  data_type: LaserScan,
  topic: scan,
  marking: true
  clearing: true
  clearing: true
