# DWAPlannerROS:

# # Robot Configuration Parameters
#   max_vel_x: 0.26
#   #-0.26????????????????????????????????????????????????
#   min_vel_x: -0.26

#   max_vel_y: 0.0
#   min_vel_y: 0.0

# # The velocity when robot is moving in a straight line
#   max_vel_trans:  0.26
#   min_vel_trans:  0.13

#   max_vel_theta: 1.82
#   min_vel_theta: 0.9

#   acc_lim_x: 0.5
#   acc_lim_y: 0.0
#   acc_lim_theta: 3.2 

# # Goal Tolerance Parametes
#   xy_goal_tolerance: 0.05
#   yaw_goal_tolerance: 0.17
#   latch_xy_goal_tolerance: false

# # Forward Simulation Parameters
#   sim_time: 2.0
#   vx_samples: 20
#   vy_samples: 0
#   vth_samples: 40
#   controller_frequency: 10.0

# # Trajectory Scoring Parameters
#   path_distance_bias: 32.0
#   goal_distance_bias: 20.0
#   occdist_scale: 0.02
#   forward_point_distance: 0.325
#   stop_time_buffer: 0.2
#   scaling_speed: 0.25
#   max_scaling_factor: 0.2

# # Oscillation Prevention Parameters
#   oscillation_reset_dist: 0.05

# # Debugging
#   publish_traj_pc : true
#   publish_cost_grid_pc: true

base_local_planner: dwa_local_planner/DWAPlannerROS
# DWAPlannerROS:
# # Robot Configuration Parameters
#   max_vel_x: 0.22
#   min_vel_x: 0.22

#   max_vel_y: 0.0
#   min_vel_y: 0.0

# # The velocity when robot is moving in a straight line
#   max_vel_trans:  0.22
#   min_vel_trans:  0.11

#   max_vel_theta: 2.75
#   min_vel_theta: 1.37

#   acc_lim_x: 2.5
#   acc_lim_y: 0.0
#   acc_lim_theta: 3.2 

# # Goal Tolerance Parametes
#   xy_goal_tolerance: 0.1
#   yaw_goal_tolerance: 0.5
#   latch_xy_goal_tolerance: false

# # Forward Simulation Parameters
#   sim_time: 1.5
#   vx_samples: 20
#   vy_samples: 0
#   vth_samples: 40
#   controller_frequency: 10.0

# # Trajectory Scoring Parameters
#   path_distance_bias: 32.0
#   goal_distance_bias: 20.0
#   occdist_scale: 0.02
#   forward_point_distance: 0.325
#   stop_time_buffer: 0.2
#   scaling_speed: 0.25
#   max_scaling_factor: 0.2

# # Oscillation Prevention Parameters
#   oscillation_reset_dist: 0.05

# # Debugging
#   publish_traj_pc : true
#   publish_cost_grid_pc: true

DWAPlannerROS:
  max_vel_trans: 0.20
  min_vel_trans: 0.01
  max_vel_x: 0.20
  min_vel_x: -0.025
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 0.30
  min_vel_theta: -0.30
  acc_lim_x: 1.25
  acc_lim_y: 0.0
  acc_lim_theta: 5
  acc_lim_trans: 1.25

  prune_plan: false

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  trans_stopped_vel: 0.1
  theta_stopped_vel: 0.1

  sim_time: 3.0
  sim_granularity: 0.1
  angular_sim_granularity: 0.1
  vx_samples: 20
  vy_samples: 0
  vth_samples: 40
  path_distance_bias: 34.0
  goal_distance_bias: 24.0
  occdist_scale: 0.05
  forward_point_distance: 0.3
  stop_time_buffer: 0.5
  scaling_speed: 0.25
  max_scaling_factor: 0.2

  twirling_scale: 0.0  
  oscillation_reset_dist: 0.05
  oscillation_reset_angle: 0.2  

  use_dwa: true
  restore_defaults: false