
global_costmap:
  #global_frame: map
  #robot_base_frame: base_footprint
  # update_frequency: 10.0
  # publish_frequency: 10.0
  # transform_tolerance: 0.5
  # width: 10
  # height: 10
  static_map: true
  rolling_window: false
  #footprint: [[0.15, 0.12], [0.15, -0.15], [-0.12, -0.15], [-0.12, 0.12]]
  
plugins:
  - {name: static,                  type: "costmap_2d::StaticLayer"}
  - {name: obstacles_laser,         type: "costmap_2d::VoxelLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
