
global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true
  footprint: [[0.15, 0.12], [0.15, -0.15], [-0.12, -0.15], [-0.12, 0.12]]
  # static_map: false
  
  # rolling_window: false
  # track_unknown_space: true

# plugins:
#   - {name: static,                  type: "costmap_2d::StaticLayer"}
#   - {name: obstacles_laser,         type: "costmap_2d::VoxelLayer"}
#   - {name: inflation,               type: "costmap_2d::InflationLayer"}
