## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: -308.0
accel_x_max: 225.0
accel_y_min: -317.0
accel_y_max: 376.0
accel_z_min: -309.0
accel_z_max: 431.0

### magnetometer
# standard calibration
magn_x_min: -3803.0
magn_x_max: 753.0
magn_y_min: -3065.0
magn_y_max: 1622.0
magn_z_min: -4426.0
magn_z_max: 1120.0

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [92.9121, 35.0553, 207.312]
magn_ellipsoid_transform: [[92.9121, 35.0553, 207.312], [92.9121, 35.0553, 207.312], [92.9121, 35.0553, 207.312]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -6.40
gyro_average_offset_y: 35.97
gyro_average_offset_z: 17.23
